--	q17
SELECT CHUYENBAY.SBDEN, COUNT(CHUYENBAY.MACB) AS SOCHUYENBAY
FROM CHUYENBAY
GROUP BY CHUYENBAY.SBDEN
ORDER BY CHUYENBAY.SBDEN ASC
GO

--Q18
SELECT CHUYENBAY.SBDI, COUNT(CHUYENBAY.MACB) AS SOCHUYENBAY
FROM CHUYENBAY
GROUP BY CHUYENBAY.SBDI
ORDER BY CHUYENBAY.SBDI ASC
GO

--Q19
SELECT CHUYENBAY.SBDI,LICHBAY.NGAYDI, COUNT(CHUYENBAY.MACB) AS SOCHUYENBAY
FROM CHUYENBAY, LICHBAY
WHERE LICHBAY.MACB = CHUYENBAY.MACB
GROUP BY CHUYENBAY.SBDI, LICHBAY.NGAYDI, LICHBAY.MACB
GO

--Q20
SELECT CHUYENBAY.SBDEN,LICHBAY.NGAYDI, COUNT(CHUYENBAY.MACB) AS SOCHUYENBAY
FROM CHUYENBAY, LICHBAY
WHERE LICHBAY.MACB = CHUYENBAY.MACB
GROUP BY CHUYENBAY.SBDEN, LICHBAY.NGAYDI, LICHBAY.MACB
GO

--Q21
SELECT LB.MACB, LB.NGAYDI, COUNT(NV.MANV) AS SONV
FROM LICHBAY LB
JOIN PHANCONG PC
ON LB.MACB = PC.MACB AND LB.NGAYDI = PC.NGAYDI
JOIN NHANVIEN NV
ON PC.MANV = NV.MANV
WHERE NV.LOAINV = 0
GROUP BY LB.MACB, LB.NGAYDI
GO

--Q22
SELECT COUNT(LICHBAY.MACB)
FROM LICHBAY, CHUYENBAY
WHERE LICHBAY.MACB = CHUYENBAY.MACB AND LICHBAY.NGAYDI = '11/01/2000' AND CHUYENBAY.SBDI = 'MIA'
GO

--Q23
SELECT LB.MACB, LB.NGAYDI, COUNT(NV.MANV) AS SONV
FROM LICHBAY LB
JOIN PHANCONG PC
ON LB.MACB = PC.MACB AND LB.NGAYDI = PC.NGAYDI
JOIN NHANVIEN NV
ON PC.MANV = NV.MANV
GROUP BY LB.MACB, LB.NGAYDI
ORDER BY SONV DESC
GO

--Q24
SELECT LB.MACB, LB.NGAYDI, COUNT(DC.MAKH) AS SOKH
FROM LICHBAY LB
JOIN DATCHO DC
ON LB.MACB = DC.MACB AND LB.NGAYDI = DC.NGAYDI
GROUP BY LB.MACB, LB.NGAYDI
ORDER BY SOKH DESC
GO

--Q25
SELECT LB.MACB, LB.NGAYDI, SUM(NV.LUONG) AS TONGLUONG
FROM LICHBAY LB
JOIN PHANCONG PC
ON LB.MACB = PC.MACB AND LB.NGAYDI = PC.NGAYDI
JOIN NHANVIEN NV
ON PC.MANV = NV.MANV
GROUP BY LB.MACB, LB.NGAYDI
ORDER BY TONGLUONG ASC
GO

--Q26
SELECT AVG(NHANVIEN.LUONG) AS LUONGTB
FROM NHANVIEN
WHERE NHANVIEN.LOAINV = 0
GO

--Q27
SELECT AVG(NHANVIEN.LUONG) AS LUONGTB
FROM NHANVIEN
WHERE NHANVIEN.LOAINV = 1
GO

SELECT LICHBAY.MALOAI, COUNT(LICHBAY.MACB)
FROM LICHBAY, CHUYENBAY
WHERE LICHBAY.MACB = CHUYENBAY.MACB AND CHUYENBAY.SBDEN = 'ORD'
GROUP BY LICHBAY.MALOAI

--Q29
SELECT CHUYENBAY.SBDI, COUNT(LICHBAY.MACB) AS SOCB
FROM CHUYENBAY, LICHBAY
WHERE CHUYENBAY.MACB = LICHBAY.MACB AND CHUYENBAY.GIODI BETWEEN '10:00' AND '20:00'
GROUP BY CHUYENBAY.SBDI
HAVING COUNT(LICHBAY.MACB) >2
GO

--Q30
SELECT NV.TEN, COUNT(PC.MANV)
FROM PHANCONG PC
JOIN NHANVIEN NV
ON PC.MANV = NV.MANV
WHERE NV.LOAINV = 1
GROUP BY PC.NGAYDI, NV.TEN
HAVING COUNT(PC.MANV) > =2
GO

--Q31
SELECT LICHBAY.MACB, LICHBAY.NGAYDI
FROM LICHBAY, DATCHO
WHERE DATCHO.MACB = LICHBAY.MACB AND LICHBAY.NGAYDI = DATCHO.NGAYDI
GROUP BY LICHBAY.MACB, LICHBAY.NGAYDI
HAVING COUNT(DATCHO.MAKH) <3
GO

--Q32
SELECT LICHBAY.SOHIEU, LICHBAY.MALOAI
FROM LICHBAY, PHANCONG
WHERE LICHBAY.MACB = PHANCONG.MACB AND LICHBAY.NGAYDI = PHANCONG.NGAYDI AND PHANCONG.MANV = '1001'
GROUP BY LICHBAY.SOHIEU, LICHBAY.MALOAI
HAVING COUNT (*) >=2
GO

--Q32
SELECT LOAIMB.HANGSX, COUNT(*) AS SOMB
FROM LOAIMB
GROUP BY LOAIMB.HANGSX
GO

