
GO
Use QLCHUYENBAY
go

--Q34
SELECT LICHBAY.SOHIEU, LICHBAY.MALOAI, LOAIMB.HANGSX
FROM LOAIMB, LICHBAY
WHERE LICHBAY.MALOAI = LOAIMB.MALOAI
GROUP BY LICHBAY.SOHIEU, LICHBAY.MALOAI, LOAIMB.HANGSX
HAVING COUNT(*) >= ALL (SELECT COUNT (*) FROM LICHBAY, LOAIMB WHERE LICHBAY.MALOAI = LOAIMB.MALOAI GROUP BY LICHBAY.SOHIEU, LICHBAY.MALOAI, LOAIMB.HANGSX)

--Q35
GO
SELECT NV.MANV,NV.TEN
FROM NHANVIEN NV, PHANCONG PC
WHERE NV.MANV = PC.MANV
GROUP BY NV.MANV, NV.TEN
HAVING COUNT(*) >= ALL (SELECT COUNT(*) FROM NHANVIEN NV, PHANCONG PC
						WHERE NV.MANV = PC.MANV
						GROUP BY NV.MANV, NV.TEN)
--Q36
GO
SELECT NV.MANV,NV.TEN, NV.DCHI, NV.DTHOAI
FROM NHANVIEN NV, PHANCONG PC
WHERE NV.MANV = PC.MANV AND NV.LOAINV = 1
GROUP BY NV.MANV, NV.TEN, NV.DCHI, NV.DTHOAI
HAVING COUNT(*) >= ALL (SELECT COUNT(*) FROM NHANVIEN NV, PHANCONG PC
						WHERE NV.MANV = PC.MANV AND NV.LOAINV = 1
						GROUP BY NV.MANV, NV.TEN, NV.DCHI, NV.DTHOAI)

--Q37
GO
SELECT CB.SBDEN, COUNT(CB.MACB) AS SOCB
FROM CHUYENBAY CB
GROUP BY CB.SBDEN
HAVING COUNT(CB.MACB) <= ALL (SELECT COUNT(CB.MACB) AS SOCB
FROM CHUYENBAY CB
GROUP BY CB.SBDEN)

--Q38
GO
SELECT CB.SBDI, COUNT(CB.MACB) AS SOCB
FROM CHUYENBAY CB
GROUP BY CB.SBDI
HAVING COUNT(CB.MACB) >= ALL (SELECT COUNT(CB.MACB) AS SOCB
FROM CHUYENBAY CB
GROUP BY CB.SBDI)

--Q39
GO
SELECT KH.MAKH, KH.TEN, KH.DCHI, KH.DTHOAI
FROM KHACHHANG KH
WHERE KH.MAKH IN
(SELECT MAKH
FROM DATCHO
GROUP BY MAKH
HAVING COUNT(*) >= ALL (SELECT COUNT(*) FROM DATCHO GROUP BY MAKH))

--Q40
GO
SELECT NV.MANV, NV.TEN,NV.LUONG
FROM NHANVIEN NV, KHANANG KN
WHERE NV.LOAINV = 1 AND NV.MANV = KN.MANV
GROUP BY NV.MANV, NV.TEN,NV.LUONG
HAVING COUNT(NV.MANV) >= ALL (SELECT COUNT(NV.MANV)
FROM NHANVIEN NV, KHANANG KN
WHERE NV.LOAINV = 1 AND NV.MANV = KN.MANV GROUP BY NV.MANV,NV.TEN,NV.LUONG)

--Q41
GO
SELECT NV.MANV, NV.TEN,NV.LUONG
FROM NHANVIEN NV
WHERE LUONG = (SELECT MAX(LUONG) FROM NHANVIEN)

--Q42
SELECT NV.TEN, NV.DCHI, PC.MACB, PC.NGAYDI 
FROM NHANVIEN NV, PHANCONG PC
WHERE NV.MANV = PC.MANV AND NV.LUONG = (SELECT MAX(LUONG) FROM NHANVIEN NV1, PHANCONG PC1 WHERE NV1.MANV = PC1.MANV AND PC.MACB = PC1.MACB AND PC.NGAYDI = PC1.NGAYDI GROUP BY PC1.MACB, PC1.NGAYDI)

GO
-- Q43 
SELECT MACB, GIODI, GIODEN
FROM CHUYENBAY
WHERE DATEDIFF(MINUTE, GIODI, (SELECT MIN(GIODI) FROM CHUYENBAY)) = 0

GO
--Q44
SELECT MACB, CAST(DATEADD(MINUTE, DATEDIFF(MINUTE, GIODI, GIODEN),0) AS TIME) AS THOIGIAN
FROM CHUYENBAY
WHERE DATEDIFF(MINUTE, DATEDIFF(MINUTE, GIODI, GIODEN), (SELECT MAX(DATEDIFF(MINUTE, GIODI, GIODEN)) FROM CHUYENBAY)) = 0
GO


--Q45
SELECT MACB, CAST(DATEADD(MINUTE, DATEDIFF(MINUTE, GIODI, GIODEN),0) AS TIME) AS THOIGIAN
FROM CHUYENBAY
WHERE DATEDIFF(MINUTE, DATEDIFF(MINUTE, GIODI, GIODEN), (SELECT MIN(DATEDIFF(MINUTE, GIODI, GIODEN)) FROM CHUYENBAY)) = 0
GO

--Q46
SELECT LB.MACB, LB.NGAYDI
FROM LICHBAY LB
WHERE LB.MACB IN
(
SELECT MACB
FROM LICHBAY
WHERE MALOAI = 'B747'
GROUP BY MACB
HAVING COUNT(NGAYDI) >= ALL (SELECT COUNT(NGAYDI) FROM LICHBAY WHERE MALOAI = 'B747' GROUP BY NGAYDI))


--Q47

SELECT PC.MACB, PC.NGAYDI, COUNT(MANV) AS SL_NV
FROM PHANCONG PC,
(
SELECT MACB, NGAYDI
FROM DATCHO
GROUP BY MACB, NGAYDI
HAVING COUNT(MAKH) > 3
) AS KH
WHERE PC.MACB = KH.MACB AND PC.NGAYDI = KH.NGAYDI
GROUP BY PC.MACB, PC.NGAYDI

GO
--Q48
SELECT NV.LOAINV, COUNT(NV.MANV) AS TONGLUONG
FROM NHANVIEN NV
GROUP BY NV.LOAINV
HAVING SUM(LUONG)>600000
GO
--Q49
SELECT DC.MACB, DC.NGAYDI, COUNT(DC.MAKH)
FROM DATCHO DC,
(
SELECT MACB, NGAYDI
FROM PHANCONG
GROUP BY MACB, NGAYDI
HAVING COUNT (MANV) > 3
) AS PC
WHERE PC.MACB = DC.MACB AND PC.NGAYDI = DC.NGAYDI
GROUP BY DC.MACB, DC.NGAYDI

GO

--Q50
SELECT MALOAI, COUNT(SOHIEU) AS SL
FROM LICHBAY
WHERE MALOAI IN
(
SELECT MALOAI
FROM MAYBAY
GROUP BY MALOAI
HAVING COUNT(SOHIEU) > 1
)
GROUP BY MALOAI