use QLGiaoVien
go

--Q64
SELECT GV.hoten
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT CV.madt
	FROM CV
	WHERE CV.madt = '006'
	EXCEPT
	SELECT TG.madt
	FROM THAMGIADT TG
	WHERE GV.magv = TG.magv AND TG.madt = '006'
)
GO

--Q65
SELECT GV.hoten
FROM GIAOVIEN GV, THAMGIADT TG, CHUDE CD, DETAI DT
WHERE GV.magv = TG.magv AND TG.madt = DT.madt AND DT.macd = CD.macd AND CD.tencd = N'Quản lí giáo dục'
GROUP BY GV.magv, GV.hoten
HAVING COUNT(DT.MADT) = (SELECT COUNT(*)
						FROM DETAI DT, CHUDE CD
						WHERE DT.macd = CD.macd AND CD.tencd = N'Quản lí giáo dục')
GO

--Q66
SELECT GV.hoten
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT DT.madt
					FROM DETAI DT
					WHERE DT.gvcndt = (SELECT GIAOVIEN.magv
										FROM GIAOVIEN
										WHERE GIAOVIEN.hoten = N'Trần Trà Hương')
					EXCEPT
					SELECT TG.MADT
					FROM THAMGIADT TG
					WHERE TG.magv = GV.MAGV)
GO
--Q67
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (SELECT *
				FROM GIAOVIEN GV, BOMON BM, KHOA K
				WHERE GV.mabm = BM.mabm AND BM.MAKHOA = K.MAKHOA AND K.makhoa = 'CNTT'
				AND NOT EXISTS (SELECT TG.MAGV
								FROM THAMGIADT TG
								WHERE TG.madt = DT.MADT AND GV.magv = TG.magv))
GO

--Q68
SELECT GV.hoten
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT CV.stt
					FROM CV, DETAI DT
					WHERE CV.MADT = DT.MADT AND DT.TENDT = N'Nghiên cứu tế bào gốc'
					EXCEPT
					SELECT TG.STT
					FROM THAMGIADT TG, DETAI DT2
					WHERE TG.MAGV = GV.MAGV AND TG.MADT = DT2.MADT AND DT2.TENDT = N'Nghiên cứu tế bào gốc'
				)
GO

--Q69
SELECT GV.hoten
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT DT.MADT 
					FROM DETAI DT
					WHERE DT.KINHPHI > 0
					EXCEPT
					SELECT TG.MADT
					FROM THAMGIADT TG
					WHERE TG.MAGV = GV.MAGV)
GO
--Q70
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (SELECT *
				FROM GIAOVIEN GV, BOMON BM, KHOA K
				WHERE GV.mabm = BM.mabm AND BM.MAKHOA = K.MAKHOA AND K.tenkhoa = N'Sinh học'
				AND NOT EXISTS (SELECT TG.MAGV
								FROM THAMGIADT TG
								WHERE TG.madt = DT.MADT AND GV.magv = TG.magv))
GO

--Q71
SELECT GV.MAGV, GV.hoten, GV.ngsinh
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT CV.STT
	FROM CV, DETAI DT1
	WHERE CV.madt = DT1.MADT AND DT1.TENDT = 'Ứng dụng hóa học xanh'
	EXCEPT
	SELECT TG.madt
	FROM THAMGIADT TG, DETAI DT2
	WHERE GV.magv = TG.magv AND TG.madt = DT2.MADT AND DT2.TENDT = 'Ứng dụng hóa học xanh'
)
GO

--Q72
SELECT GV.MAGV, GV.HOTEN, BM.TENBM, GVQL.HOTEN AS GVQLCM
FROM GIAOVIEN GV, BOMON BM, GIAOVIEN GVQL
WHERE	GV.MABM = BM.MABM AND GV.GVQLCM = GVQL.MAGV AND
 NOT EXISTS (		 SELECT DT.MADT
					FROM  DETAI DT, CHUDE CD
					WHERE DT.MACD = CD.MACD AND CD.TENCD =N'Nghiên cứu phát triển'
					EXCEPT 
					SELECT TG.MADT
					FROM THAMGIADT TG
					WHERE TG.MAGV = GV.MAGV )
GO

--q73
SELECT GV.hoten, GV.ngsinh, K.TENKHOA, GVCNK.HOTEN AS TRUONGKHOA
FROM GIAOVIEN GV, BOMON BM, KHOA K, GIAOVIEN GVCNK
WHERE GV.mabm = BM.mabm AND BM.makhoa = K.MAKHOA AND K.truongkhoa = GVCNK.magv
AND NOT EXISTS(SELECT DISTINCT TG1.madt 
				FROM THAMGIADT TG1, GIAOVIEN GV1
				WHERE TG1.magv = GV1.magv AND GV1.hoten = N'Nguyễn Hoài An'
				EXCEPT
				SELECT DISTINCT TG2.MADT
				FROM THAMGIADT TG2
				WHERE GV.MAGV =TG2.MAGV)
GO

--Q74
SELECT	GV2.hoten
	FROM GIAOVIEN GV2, BOMON BM, KHOA K
	WHERE GV2.mabm = BM.mabm AND BM.makhoa = K.makhoa AND K.tenkhoa = N'Công nghệ thông tin'
	AND NOT EXISTS (
		SELECT TG1.madt, TG1.stt
		FROM THAMGIADT TG1
		WHERE TG1.MAGV = ANY (
			SELECT TRBM.magv
			FROM GIAOVIEN TRBM, BOMON BM1
			WHERE BM1.truongbm = TRBM.magv AND BM1.mabm = ANY (SELECT	BM.mabm
				FROM GIAOVIEN GV, BOMON BM, KHOA K
				WHERE GV.mabm = BM.mabm AND BM.makhoa = K.makhoa AND K.tenkhoa = N'Công nghệ thông tin'
				GROUP BY BM.mabm
				HAVING COUNT(*) >= ALL (SELECT	COUNT(*)
				FROM GIAOVIEN GV, BOMON BM, KHOA K
				WHERE GV.mabm = BM.mabm AND BM.makhoa = K.makhoa AND K.tenkhoa = N'Công nghệ thông tin'
				GROUP BY BM.mabm)))
		EXCEPT
		SELECT TG2.madt, TG2.stt
		FROM THAMGIADT TG2
		WHERE TG2.MAGV = GV2.magv
	)
	GO


