use QLGIAOVIEN
GO

ALTER TABLE DETAI
ADD SOGV INT
GO

CREATE PROCEDURE SP_UPDATE_SOGV_DT @MADT VARCHAR(3)
AS
	DECLARE @SOGV INT
	SET @SOGV = (SELECT COUNT(DISTINCT MAGV) FROM THAMGIADT WHERE madt = @MADT)

	UPDATE DETAI
	SET SOGV = @SOGV
	WHERE madt = @MADT
GO

EXEC SP_UPDATE_SOGV_DT '001'
GO

EXEC SP_UPDATE_SOGV_DT '002'
GO

CREATE PROCEDURE SP_PHANCONG @MAGV VARCHAR(3), @MADT VARCHAR(3), @SOTT INT
AS
	IF (NOT EXISTS(SELECT * FROM GIAOVIEN WHERE MAGV = @MAGV))
	BEGIN
		RAISERROR(N'GIÁO VIÊN KHÔNG TỒN TẠI',15,1)
		RETURN
	END

	IF (NOT EXISTS(SELECT * FROM CV WHERE @MADT = MADT AND @SOTT = stt))
	BEGIN
		RAISERROR(N'CÔNG VIỆC K TỒN TẠI',15,1)
		RETURN
	END

	IF ((SELECT MABM FROM GIAOVIEN WHERE MAGV = @MAGV) <> (SELECT MABM FROM GIAOVIEN WHERE MAGV = (SELECT gvcndt FROM DETAI WHERE madt = @MADT)))
	BEGIN
		RAISERROR(N'GIÁO VIÊN KHÔNG CÙNG BỘ MÔN VỚI GVCNDT',15,1)
		RETURN
	END

	IF (NOT EXISTS (SELECT * FROM THAMGIADT WHERE MAGV = @MAGV AND MADT = @MADT AND STT = @SOTT))
	BEGIN
		INSERT INTO THAMGIADT(MAGV, MADT, STT) VALUES(@MAGV, @MADT,@SOTT)
		PRINT('PHÂN CÔNG THÀNH CÔNG')
	END
GO

EXEC SP_PHANCONG '006','001',2
go

CREATE FUNCTION FN_DEMSODTNGIEMTHU (@MABM VARCHAR(4))
RETURNS INT
AS
	BEGIN
	RETURN (SELECT COUNT(*) FROM DETAI DT 
	JOIN GIAOVIEN GV
	ON DT.gvcndt = GV.magv
	WHERE ngaykt IS NOT NULL AND mabm = @MABM)
	END

	GO

PRINT dbo.FN_DEMSODTNGIEMTHU ('CNTT')
GO

Create function fn_DemSoDTPTrach (@mabm varchar(4))
Returns int
As
Begin
Return (select count(*) from detai dt join giaovien gv on dt.gvcndt = gv.magv
where mabm = @mabm)
End
GO

CREATE FUNCTION FN_DEMSOCV (@MAGV VARCHAR(3), @MADT VARCHAR(3))
RETURNS INT
AS
BEGIN
	RETURN (SELECT COUNT(*) FROM THAMGIADT WHERE MAGV = @MAGV AND madt = @MADT)
END
GO

PRINT DBO.FN_DEMSOCV('001', '002')
GO

CREATE PROCEDURE SP_PHANCONGCV1 @MAGV VARCHAR(3), @MADT VARCHAR(3), @SOTT INT
AS
BEGIN
	IF (NOT EXISTS (SELECT * FROM GIAOVIEN WHERE MAGV = @MAGV))
	BEGIN
		RAISERROR(N'GIÁO VIÊN KHÔNG TỒN TẠI',15,1)
		RETURN
	END

	IF (NOT EXISTS (SELECT * FROM CV WHERE MADT = @MADT AND STT = @SOTT))
	BEGIN
		RAISERROR(N'CÔNG VIỆC KHÔNG TỒN TẠI',15,1)
		RETURN
	END

	IF ((SELECT COUNT(*) FROM THAMGIADT WHERE MAGV = @MAGV AND madt = @MADT) >= 3)
	BEGIN
		RAISERROR(N'ĐÃ THAM GIA QUÁ SỐ LUỌNG',15,1)
		RETURN
	END

	IF (NOT EXISTS(SELECT * FROM THAMGIADT WHERE MAGV = @MAGV AND madt = @MADT AND STT =@SOTT))
	BEGIN
		PRINT(N'ĐÃ PHÂN CÔNG')
		INSERT INTO THAMGIADT(magv, madt, STT) VALUES (@MAGV, @MADT, @SOTT)
		RETURN
	END
END
GO

--
SELECT BM.TENBM, (SELECT COUNT(*) 
					FROM GIAOVIEN GV
					WHERE GV.mabm = BM.mabm) AS SO_GV
FROM BOMON BM
GO

SELECT HOTEN
FROM GIAOVIEN
WHERE GIAOVIEN.magv NOT IN (SELECT magv FROM NGUOI_THAN)
GO

SELECT *
FROM GIAOVIEN
WHERE GIAOVIEN.magv IN (SELECT MAGV FROM THAMGIADT)
GO

SELECT MABM
FROM GIAOVIEN
GROUP BY MABM
HAVING COUNT(*) >= ALL (SELECT COUNT(*)
						FROM GIAOVIEN
						GROUP BY MABM)
GO

SELECT BM.TENBM, TBM.hoten, COUNT(*) AS SLGV
FROM GIAOVIEN GV, BOMON BM, GIAOVIEN TBM
WHERE GV.MABM = BM.MABM
GROUP BY GV.MABM
HAVING COUNT(*) >= ALL (SELECT COUNT(*) FROM GIAOVIEN GROUP BY MABM)
go

SELECT DISTINCT TG1.MAGV
FROM THAMGIADT TG1
WHERE NOT EXISTS (
				(SELECT MADT FROM DETAI)
				EXCEPT
				(SELECT MADT
				FROM THAMGIADT TG2
				WHERE TG2.MAGV = TG1.MAGV)
)
GO

select TENDT, CAPQL
from DETAI
where datediff(D, detai.ngaybd, getdate()) < 0